// Curated index of periods and artists. Only names/date-ranges/colors live here —
// every bio, image, story and fact is fetched from Wikipedia/Wikimedia at ingest time.

export interface SeedPeriod {
  slug: string;
  name: string;
  wikiTitle: string; // English Wikipedia article describing the period
  startYear: number;
  endYear: number;
  color: string; // accent used across timeline views
  artists: string[]; // English Wikipedia article titles
}

export const PERIODS: SeedPeriod[] = [
  {
    slug: "chinese-painting",
    name: "Chinese Painting",
    wikiTitle: "Chinese painting",
    startYear: 950,
    endYear: 1950,
    color: "#3b5b4b",
    artists: [
      "Shen Zhou",
      "Shitao",
      "Tang Yin",
      "Emperor Huizong of Song",
      "Dong Qichang",
      "Wen Zhengming",
      "Guo Xi",
      "Bada Shanren",
      "Wang Yuanqi",
      "Wang Meng (painter)",
      "Ni Zan",
      "Wu Changshuo",
      "Wang Shimin",
      "Fan Kuan",
      "Ma Yuan (painter)",
      "Qian Xuan",
      "Xu Beihong",
      "Qi Baishi",
      "Huang Gongwang",
      "Juran (painter)",
      "Li Cheng (painter)",
      "Cui Bai",
      "Wang Hui (Qing dynasty)",
      "Qiu Ying",
      "Zhao Mengfu",
      "Yun Shouping",
      "Chen Hongshou"
    ]
  },
  {
    slug: "medieval-gothic",
    name: "Medieval & Gothic",
    wikiTitle: "Gothic art",
    startYear: 1200,
    endYear: 1400,
    color: "#7a5c3e",
    artists: [
      "Giotto",
      "Cimabue",
      "Duccio",
      "Simone Martini",
      "Gentile da Fabriano",
      "Pietro Lorenzetti",
      "Pisanello",
      "Ambrogio Lorenzetti",
      "Andrei Rublev",
      "Dionisius"
    ]
  },
  {
    slug: "persian-miniature",
    name: "Persian Miniature",
    wikiTitle: "Persian miniature",
    startYear: 1300,
    endYear: 1700,
    color: "#2a8c8c",
    artists: [
      "Reza Abbasi",
      "Sultan Mohammed",
      "Aqa Mirak"
    ]
  },
  {
    slug: "early-renaissance",
    name: "Early Renaissance",
    wikiTitle: "Renaissance art",
    startYear: 1400,
    endYear: 1495,
    color: "#9c6b30",
    artists: [
      "Sandro Botticelli",
      "Fra Angelico",
      "Masaccio",
      "Filippo Lippi",
      "Piero della Francesca",
      "Andrea Mantegna",
      "Giovanni Bellini",
      "Pietro Perugino",
      "Paolo Uccello",
      "Andrea del Castagno",
      "Antonio del Pollaiuolo",
      "Antonello da Messina",
      "Gentile Bellini",
      "Filippino Lippi",
      "Pinturicchio",
      "Luca Signorelli",
      "Vittore Carpaccio",
      "Piero di Cosimo",
      "Carlo Crivelli",
      "Domenico Ghirlandaio",
      "Benozzo Gozzoli",
      "Nuno Gonçalves"
    ]
  },
  {
    slug: "japanese-painting",
    name: "Japanese Painting",
    wikiTitle: "Japanese painting",
    startYear: 1400,
    endYear: 1900,
    color: "#9c2f4f",
    artists: [
      "Sesshū Tōyō",
      "Yosa Buson",
      "Maruyama Ōkyo",
      "Ogata Kōrin",
      "Tawaraya Sōtatsu",
      "Kanō Tan'yū",
      "Hashimoto Gahō",
      "Shibata Zeshin",
      "Ike no Taiga",
      "Kanō Eitoku",
      "Watanabe Kazan",
      "Hakuin Ekaku",
      "Yamamoto Baiitsu",
      "Tomioka Tessai",
      "Tenshō Shūbun",
      "Itō Jakuchū",
      "Sakai Hōitsu"
    ]
  },
  {
    slug: "northern-renaissance",
    name: "Northern Renaissance",
    wikiTitle: "Northern Renaissance",
    startYear: 1420,
    endYear: 1580,
    color: "#56704f",
    artists: [
      "Jan van Eyck",
      "Rogier van der Weyden",
      "Hans Memling",
      "Hieronymus Bosch",
      "Albrecht Dürer",
      "Lucas Cranach the Elder",
      "Hans Holbein the Younger",
      "Pieter Bruegel the Elder",
      "Petrus Christus",
      "Gerard David",
      "Quentin Matsys",
      "Albrecht Altdorfer",
      "Hans Baldung",
      "Matthias Grünewald",
      "Robert Campin",
      "Hugo van der Goes",
      "Dieric Bouts",
      "Geertgen tot Sint Jans",
      "Stefan Lochner",
      "Joachim Patinir",
      "Karel van Mander"
    ]
  },
  {
    slug: "cretan-school",
    // the Ionian (Heptanese) school succeeded the Cretan school after 1669 and hangs with it
    name: "Cretan & Ionian Schools",
    wikiTitle: "Cretan school",
    startYear: 1450,
    endYear: 1830,
    color: "#9a7b2c",
    artists: [
      "Michael Damaskinos",
      "Theodore Poulakis",
      "Georgios Klontzas",
      "Andreas Ritzos",
      "Angelos Akotantos",
      "Emmanuel Tzanes",
      "Nikolaos Tzafouris",
      "Angelos Pitzamanos",
      "Thomas Bathas",
      "Franghias Kavertzas",
      "Ieremias Palladas",
      "Elias Moskos",
      "Leos Moskos",
      "Ioannis Moskos",
      "Victor (iconographer)",
      "Philotheos Skoufos",
      "Konstantinos Tzanes",
      "Stephanos Tzangarolas",
      "Panagiotis Doxaras",
      "Andreas Karantinos",
      "Nikolaos Kallergis",
      "Nikolaos Doxaras",
      "Stylianos Stavrakis",
      "Spiridione Roma",
      "Efstathios Karousos",
      "Nikolaos Koutouzis",
      "Ioannis Kornaros",
      "Nikolaos Kantounis"
    ]
  },
  {
    slug: "high-renaissance",
    name: "High Renaissance",
    wikiTitle: "High Renaissance",
    startYear: 1495,
    endYear: 1530,
    color: "#b08020",
    artists: [
      "Leonardo da Vinci",
      "Michelangelo",
      "Raphael",
      "Titian",
      "Giorgione",
      "Antonio da Correggio",
      "Andrea del Sarto",
      "Lorenzo Lotto",
      "Sebastiano del Piombo",
      "Giulio Romano",
      "Cima da Conegliano",
      "Moretto da Brescia",
      "Palma Vecchio",
      "Fra Bartolomeo",
      "Alonso Berruguete"
    ]
  },
  {
    slug: "mannerism",
    name: "Mannerism",
    wikiTitle: "Mannerism",
    startYear: 1520,
    endYear: 1600,
    color: "#8e7c4a",
    artists: [
      "Pontormo",
      "Parmigianino",
      "Bronzino",
      "Sofonisba Anguissola",
      "Giuseppe Arcimboldo",
      "Tintoretto",
      "Paolo Veronese",
      "El Greco",
      "Rosso Fiorentino",
      "Domenico Beccafumi",
      "Giorgio Vasari",
      "Federico Barocci",
      "Lavinia Fontana"
    ]
  },
  {
    slug: "indian-painting",
    name: "Indian Painting",
    wikiTitle: "Indian painting",
    startYear: 1550,
    endYear: 1950,
    color: "#e0a526",
    artists: [
      "Abanindranath Tagore",
      "Mir Sayyid Ali",
      "Ustad Mansur",
      "Nainsukh",
      "Basawan",
      "Manaku of Guler",
      "Govardhan (artist)",
      "Abu'l-Hasan (artist)",
      "Nihâl Chand"
    ]
  },
  {
    slug: "cusco-school",
    name: "Colonial Latin American Painting",
    wikiTitle: "Latin American art",
    startYear: 1550,
    endYear: 1800,
    color: "#8e5a9e",
    artists: [
      "Miguel Cabrera (painter)",
      "Cristóbal de Villalpando",
      "Juan Correa"
    ]
  },
  {
    slug: "baroque",
    name: "Baroque",
    wikiTitle: "Baroque painting",
    startYear: 1600,
    endYear: 1725,
    color: "#6e3b23",
    artists: [
      "Caravaggio",
      "Peter Paul Rubens",
      "Artemisia Gentileschi",
      "Diego Velázquez",
      "Anthony van Dyck",
      "Nicolas Poussin",
      "Claude Lorrain",
      "Georges de La Tour",
      "Francisco de Zurbarán",
      "Bartolomé Esteban Murillo",
      "Annibale Carracci",
      "Guido Reni",
      "Guercino",
      "Jusepe de Ribera",
      "Simon Vouet",
      "Philippe de Champaigne",
      "Jacob Jordaens",
      "Jan Brueghel the Elder",
      "Luca Giordano",
      "Godfrey Kneller",
      "Mattia Preti",
      "Orazio Gentileschi",
      "Salvator Rosa",
      "Pietro da Cortona",
      "Agostino Carracci",
      "Domenichino",
      "Ludovico Carracci",
      "Frans Snyders",
      "John Michael Wright",
      "Juan de Valdés Leal",
      "Alonso Cano",
      "Claudio Coello",
      "Juan Carreño de Miranda",
      "Juan Sánchez Cotán",
      "Francisco Herrera the Elder",
      "Francisco Pacheco",
      "Pieter Brueghel the Younger",
      "Adriaen Brouwer"
    ]
  },
  {
    slug: "dutch-golden-age",
    name: "Dutch Golden Age",
    wikiTitle: "Dutch Golden Age painting",
    startYear: 1588,
    endYear: 1720,
    color: "#3f5f78",
    artists: [
      "Rembrandt",
      "Johannes Vermeer",
      "Frans Hals",
      "Judith Leyster",
      "Jan Steen",
      "Pieter de Hooch",
      "Jacob van Ruisdael",
      "Gerard ter Borch",
      "Gerrit Dou",
      "Gerard van Honthorst",
      "Gabriël Metsu",
      "Aelbert Cuyp",
      "Carel Fabritius",
      "Willem Claesz. Heda",
      "Rachel Ruysch",
      "Clara Peeters",
      "Hendrick Avercamp",
      "Meindert Hobbema",
      "Paulus Potter",
      "Emanuel de Witte",
      "Ambrosius Bosschaert"
    ]
  },
  {
    slug: "ukiyo-e",
    name: "Ukiyo-e",
    wikiTitle: "Ukiyo-e",
    startYear: 1670,
    endYear: 1900,
    color: "#1f3f6e",
    artists: [
      "Hokusai",
      "Hiroshige",
      "Utamaro",
      "Suzuki Harunobu",
      "Utagawa Kuniyoshi",
      "Tsukioka Yoshitoshi",
      "Sharaku",
      "Kunisada"
    ]
  },
  {
    slug: "rococo",
    name: "Rococo",
    wikiTitle: "Rococo",
    startYear: 1700,
    endYear: 1780,
    color: "#c98da4",
    artists: [
      "Antoine Watteau",
      "François Boucher",
      "Jean-Honoré Fragonard",
      "Giovanni Battista Tiepolo",
      "Canaletto",
      "Jean Siméon Chardin",
      "William Hogarth",
      "Thomas Gainsborough",
      "Joseph Wright of Derby",
      "Joshua Reynolds",
      "Bernardo Bellotto",
      "Claude-Joseph Vernet",
      "John Singleton Copley",
      "Jean-Baptiste Greuze",
      "Pompeo Batoni",
      "George Stubbs",
      "Francesco Guardi",
      "Giovanni Paolo Panini",
      "Rosalba Carriera",
      "Pietro Longhi",
      "Richard Wilson (painter)",
      "George Romney (painter)",
      "Allan Ramsay (artist)",
      "Paul Sandby"
    ]
  },
  {
    slug: "neoclassicism",
    name: "Neoclassicism",
    wikiTitle: "Neoclassicism",
    startYear: 1760,
    endYear: 1830,
    color: "#5f7d8c",
    artists: [
      "Jacques-Louis David",
      "Jean-Auguste-Dominique Ingres",
      "Élisabeth Vigée Le Brun",
      "Angelica Kauffman",
      "Antoine-Jean Gros",
      "Benjamin West",
      "François Gérard",
      "Gilbert Stuart",
      "Anne-Louis Girodet de Roussy-Trioson",
      "Anton Raphael Mengs",
      "Marie-Guillemine Benoist",
      "Henry Raeburn",
      "Thomas Rowlandson",
      "Christoffer Wilhelm Eckersberg",
      "Gerasimos Pitsamanos"
    ]
  },
  {
    slug: "romanticism",
    name: "Romanticism",
    wikiTitle: "Romanticism",
    startYear: 1780,
    endYear: 1850,
    color: "#7d4b66",
    artists: [
      "Francisco Goya",
      "Henry Fuseli",
      "William Blake",
      "Eugène Delacroix",
      "J. M. W. Turner",
      "John Constable",
      "Caspar David Friedrich",
      "Théodore Géricault",
      "Francesco Hayez",
      "Ivan Aivazovsky",
      "Emanuel Leutze",
      "Thomas Lawrence",
      "Paul Delaroche",
      "Horace Vernet",
      "William Etty",
      "Gustave Doré",
      "Carl Spitzweg",
      "David Wilkie (artist)",
      "Edwin Landseer",
      "Théodore Chassériau",
      "John Martin (painter)",
      "Johan Christian Dahl",
      "Richard Parkes Bonington",
      "Samuel Palmer",
      "David Roberts (painter)",
      "Daniel Maclise",
      "John Sell Cotman",
      "Wilhelm Marstrand",
      "Martinus Rørbye",
      "Constantin Hansen",
      "Christen Købke",
      "Raden Saleh",
      "Dionysios Tsokos"
    ]
  },
  {
    slug: "hudson-river-school",
    name: "Hudson River School",
    wikiTitle: "Hudson River School",
    startYear: 1825,
    endYear: 1880,
    color: "#6f7d43",
    artists: [
      "Thomas Cole",
      "Frederic Edwin Church",
      "Albert Bierstadt",
      "Thomas Moran"
    ]
  },
  {
    slug: "academic-art",
    name: "Academic Art",
    wikiTitle: "Academic art",
    startYear: 1830,
    endYear: 1900,
    color: "#94705a",
    artists: [
      "Karl Bryullov",
      "Jean-Léon Gérôme",
      "Alexandre Cabanel",
      "William-Adolphe Bouguereau",
      "Frederic Leighton",
      "Jan Matejko",
      "Raja Ravi Varma",
      "Franz Xaver Winterhalter",
      "Ernest Meissonier",
      "Lawrence Alma-Tadema",
      "James Tissot",
      "Osman Hamdi Bey",
      "William Powell Frith",
      "Henryk Siemiradzki",
      "Juan Luna",
      "Hans Makart",
      "Theodoros Vryzakis",
      "Edward Lear",
      "Vasily Polenov",
      "Vasily Vereshchagin",
      "Konstantin Makovsky",
      "Alexei Savrasov",
      "Vasily Perov",
      "Konstantin Savitsky",
      "Victor Meirelles",
      "Pedro Américo",
      "José María Velasco Gómez",
      "Cornelius Krieghoff",
      "Konstantinos Volanakis",
      "Nikolaos Gyzis",
      "Nicolae Grigorescu",
      "Mihály Munkácsy",
      "Nikiforos Lytras",
      "Théodore Ralli",
      "Iakovos Rizos",
      "Symeon Savvidis",
      "Nikolaos Vokos",
      "Georgios Roilos",
      "Spyridon Prosalentis",
      "Charalambos Pachis",
      "Ioannis Zacharias",
      "Emmanuel Zairis",
      "Nikolaos Himonas"
    ]
  },
  {
    slug: "realism",
    name: "Realism",
    wikiTitle: "Realism (art movement)",
    startYear: 1840,
    endYear: 1880,
    color: "#5c6b4f",
    artists: [
      "Jean-Baptiste-Camille Corot",
      "Honoré Daumier",
      "Gustave Courbet",
      "Jean-François Millet",
      "Ivan Shishkin",
      "Ivan Kramskoi",
      "Ilya Repin",
      "James McNeill Whistler",
      "Winslow Homer",
      "Thomas Eakins",
      "John Singer Sargent",
      "Adolph Menzel",
      "Isaac Levitan",
      "Albert Edelfelt",
      "Arkhip Kuindzhi",
      "Henry Ossawa Tanner",
      "Rosa Bonheur",
      "Jules Bastien-Lepage",
      "Wilhelm Leibl",
      "George Caleb Bingham",
      "Jacek Malczewski",
      "Viktor Vasnetsov",
      "Vasily Surikov",
      "Almeida Júnior",
      "Jozef Israëls",
      "Anton Mauve",
      "Jacob Maris",
      "Willem de Zwart",
      "Carl Larsson",
      "Anna Ancher",
      "Michael Ancher",
      "Christian Krohg",
      "Kamal-ol-molk",
      "Candido Portinari",
      "Rodolfo Amoedo",
      "Tivadar Csontváry Kosztka",
      "Józef Chełmoński",
      "Georgios Jakobides",
      "Polychronis Lembesis",
      "Ioannis Altamouras",
      "Vasileios Hatzis",
      "Yiannis Poulakas",
      "Angelos Giallinas"
    ]
  },
  {
    slug: "pre-raphaelites",
    name: "Pre-Raphaelites",
    wikiTitle: "Pre-Raphaelite Brotherhood",
    startYear: 1848,
    endYear: 1900,
    color: "#8a4f5c",
    artists: [
      "Dante Gabriel Rossetti",
      "John Everett Millais",
      "Edward Burne-Jones",
      "John William Waterhouse",
      "Ford Madox Brown",
      "William Holman Hunt",
      "Evelyn De Morgan",
      "John Atkinson Grimshaw",
      "Arthur Hughes (artist)"
    ]
  },
  {
    slug: "impressionism",
    name: "Impressionism",
    wikiTitle: "Impressionism",
    startYear: 1860,
    endYear: 1895,
    color: "#6f8fc9",
    artists: [
      "Claude Monet",
      "Pierre-Auguste Renoir",
      "Edgar Degas",
      "Édouard Manet",
      "Camille Pissarro",
      "Alfred Sisley",
      "Berthe Morisot",
      "Mary Cassatt",
      "Gustave Caillebotte",
      "Frédéric Bazille",
      "Henri Fantin-Latour",
      "Giovanni Boldini",
      "Peder Severin Krøyer",
      "Joaquín Sorolla",
      "Childe Hassam",
      "Max Liebermann",
      "William Merritt Chase",
      "Anders Zorn",
      "Tom Roberts",
      "Arthur Streeton",
      "Valentin Serov",
      "Walter Sickert",
      "Stanisław Wyspiański",
      "Mikhail Nesterov",
      "Léon Bakst",
      "Marie Bashkirtseff",
      "Niko Pirosmani",
      "Isaac Israëls",
      "George Hendrik Breitner",
      "Johan Jongkind",
      "Helene Schjerfbeck",
      "Frits Thaulow",
      "Pedro Figari",
      "Frederick McCubbin",
      "Charles Conder",
      "Olga Boznańska",
      "Périclès Pantazis"
    ]
  },
  {
    slug: "post-impressionism",
    name: "Post-Impressionism",
    wikiTitle: "Post-Impressionism",
    startYear: 1885,
    endYear: 1910,
    color: "#d9913d",
    artists: [
      "Vincent van Gogh",
      "Paul Cézanne",
      "Paul Gauguin",
      "Georges Seurat",
      "Paul Signac",
      "Henri de Toulouse-Lautrec",
      "Henri Rousseau",
      "Pierre Bonnard",
      "Théo van Rysselberghe",
      "Suzanne Valadon",
      "Émile Bernard",
      "Édouard Vuillard",
      "Konstantinos Maleas",
      "Theophilos Hatzimihail"
    ]
  },
  {
    slug: "symbolism",
    name: "Symbolism & Art Nouveau",
    wikiTitle: "Symbolism (movement)",
    startYear: 1880,
    endYear: 1915,
    color: "#b39235",
    artists: [
      "Gustave Moreau",
      "Arnold Böcklin",
      "Mikhail Vrubel",
      "Gustav Klimt",
      "James Ensor",
      "George Frederic Watts",
      "Pierre Puvis de Chavannes",
      "Akseli Gallen-Kallela",
      "Vilhelm Hammershøi",
      "Alphonse Mucha",
      "Odilon Redon",
      "Ferdinand Hodler",
      "Maurice Denis",
      "William Orpen",
      "Gwen John",
      "Harold Gilman",
      "Spencer Gore (artist)",
      "Nicholas Roerich",
      "Boris Kustodiev",
      "Kuzma Petrov-Vodkin",
      "Mikalojus Konstantinas Čiurlionis",
      "Jan Toorop",
      "Hugo Simberg",
      "Panos Aravantinos"
    ]
  },
  {
    slug: "fauvism",
    name: "Fauvism",
    wikiTitle: "Fauvism",
    startYear: 1904,
    endYear: 1910,
    color: "#d0603a",
    artists: [
      "Henri Matisse",
      "André Derain",
      "Raoul Dufy"
    ]
  },
  {
    slug: "expressionism",
    name: "Expressionism",
    wikiTitle: "Expressionism",
    startYear: 1905,
    endYear: 1935,
    color: "#b3452f",
    artists: [
      "Edvard Munch",
      "Ernst Ludwig Kirchner",
      "Egon Schiele",
      "Oskar Kokoschka",
      "Franz Marc",
      "Amedeo Modigliani",
      "Marc Chagall",
      "Otto Dix",
      "Max Beckmann",
      "Lovis Corinth",
      "August Macke",
      "George Grosz",
      "Amrita Sher-Gil",
      "Emil Nolde",
      "Paula Modersohn-Becker",
      "Alexej von Jawlensky",
      "Stanisław Ignacy Witkiewicz",
      "Natalia Goncharova",
      "El Lissitzky",
      "Pavel Filonov",
      "Chaïm Soutine",
      "Josef Čapek",
      "Sonia Delaunay",
      "John Bauer (illustrator)",
      "Kurt Schwitters",
      "Nikolaos Lytras"
    ]
  },
  {
    slug: "cubism",
    name: "Cubism",
    wikiTitle: "Cubism",
    startYear: 1907,
    endYear: 1925,
    color: "#4f6b6b",
    artists: [
      "Pablo Picasso",
      "Georges Braque",
      "Juan Gris",
      "Fernand Léger",
      "Marcel Duchamp",
      "Robert Delaunay",
      "Umberto Boccioni",
      "Jean Metzinger",
      "Albert Gleizes",
      "Francis Picabia",
      "Giacomo Balla",
      "Tamara de Lempicka"
    ]
  },
  {
    slug: "abstract-art",
    name: "Abstract Art",
    wikiTitle: "Abstract art",
    startYear: 1910,
    endYear: 1945,
    color: "#2f5d8a",
    artists: [
      "Wassily Kandinsky",
      "Kazimir Malevich",
      "Piet Mondrian",
      "Paul Klee",
      "Theo van Doesburg",
      "Hilma af Klint",
      "František Kupka"
    ]
  },
  {
    slug: "surrealism",
    name: "Surrealism",
    wikiTitle: "Surrealism",
    startYear: 1924,
    endYear: 1955,
    color: "#4a5a8a",
    artists: [
      "Giorgio de Chirico",
      "Salvador Dalí",
      "René Magritte",
      "Max Ernst",
      "Joan Miró",
      "Frida Kahlo",
      "Paul Delvaux",
      "Leonora Carrington",
      "László Moholy-Nagy"
    ]
  },
  {
    slug: "american-modernism",
    name: "American Modernism",
    wikiTitle: "American modernism",
    startYear: 1913,
    endYear: 1960,
    color: "#7592b8",
    artists: [
      "Edward Hopper",
      "Georgia O'Keeffe",
      "Norman Rockwell",
      "Grant Wood",
      "Andrew Wyeth",
      "Grandma Moses",
      "Thomas Hart Benton (painter)",
      "George Bellows",
      "Charles Demuth"
    ]
  },
  {
    slug: "group-of-seven",
    name: "Group of Seven",
    wikiTitle: "Group of Seven (artists)",
    startYear: 1913,
    endYear: 1935,
    color: "#4f7a3a",
    artists: [
      "Emily Carr",
      "Tom Thomson",
      "A. Y. Jackson",
      "Frank Johnston (artist)",
      "Frederick Varley"
    ]
  },
  {
    slug: "mexican-muralism",
    name: "Mexican Muralism",
    wikiTitle: "Mexican muralism",
    startYear: 1920,
    endYear: 1970,
    color: "#a35f2d",
    artists: [
      "Diego Rivera",
      "David Alfaro Siqueiros",
      "Rufino Tamayo",
      "José Clemente Orozco"
    ]
  },
  {
    slug: "abstract-expressionism",
    name: "Abstract Expressionism",
    wikiTitle: "Abstract expressionism",
    startYear: 1943,
    endYear: 1965,
    color: "#8a3a3a",
    artists: [
      "Jackson Pollock",
      "Mark Rothko",
      "Willem de Kooning",
      "Barnett Newman",
      "Joan Mitchell"
    ]
  },
  {
    slug: "pop-art",
    name: "Pop Art",
    wikiTitle: "Pop art",
    startYear: 1955,
    endYear: 1975,
    color: "#c94f7c",
    artists: [
      "Andy Warhol",
      "Roy Lichtenstein",
      "David Hockney",
      "Jasper Johns"
    ]
  },
  {
    slug: "contemporary",
    name: "Contemporary",
    wikiTitle: "Contemporary art",
    startYear: 1945,
    endYear: 2026,
    color: "#3f7d6e",
    artists: [
      "Francis Bacon (artist)",
      "Lucian Freud",
      "Jean-Michel Basquiat",
      "Keith Haring",
      "Banksy",
      "Gerhard Richter",
      "Jean Dubuffet",
      "fr:Yannis Gaïtis"
    ]
  }
];

// Greek painters left out for now: still in copyright with no free images on Commons or WikiArt, so their
// galleries would be empty or hold one © placard. Add them back when a free catalogue appears (as Yannis
// Gaïtis's did): Konstantinos Parthenis, George Bouzianis, Nikos Hadjikyriakos-Ghikas, Nikos Engonopoulos,
// Yannis Tsarouchis, Yiannis Moralis, Spyridon Vikatos (d. 1960); Spyros Papaloukas (public domain from 2028). Nikolaos Xydias Typaldos has
// no sourced works yet.

// Catalogues released on Commons under a free licence by an artist's rights holders, for artists still in
// copyright: their works hang with images (ingest.ts commonsCatalogue). Keys are seed titles; a language
// prefix ("fr:") names an artist without an English article.
export const COMMONS_CATALOGUES: Record<string, string[]> = {
  // catalogue raisonné released CC BY-SA 4.0 by Loretta Gaïtis (VRT permission confirmed)
  "fr:Yannis Gaïtis": ["Category:Paintings by Yannis Gaïtis"],
};

// Specific painting articles to include for artists whose Wikidata/category
// coverage misses works that do have illustrated Wikipedia articles.
export const EXTRA_PAINTINGS: Record<string, string[]> = {
  // Famous works whose Wikidata items aren't linked to the artist (or carry
  // another class) and that aren't in the artist's "Paintings by" category.
  "Francisco Goya": ["La maja desnuda"],
  "Pieter Bruegel the Elder": ["Landscape with the Fall of Icarus"],
  "Willem de Kooning": [
    "Police Gazette (painting)",
    "Woman VI",
    "Woman I",
    "Woman III",
  ],
  "David Hockney": [
    "A Bigger Splash",
    "Mr and Mrs Clark and Percy",
    "Bigger Trees Near Warter",
    "Portrait of an Artist (Pool with Two Figures)",
    "Peter Getting Out of Nick's Pool",
  ],
};
